### ISSUE TITLE
Practica de Calidad-Café Huerto

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-de-calidad-entrevista-gp#1]
[Plan de Calidad_Final_Edwin, Alexis, Ivan, Taoli.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calidad-entrevista-gp/files/7338450/Plan.de.Calidad_Final_Edwin.Alexis.Ivan.Taoli.pdf)

**Comment by Jaci14** [comment]
Calificación: 20%
Cumple con cada uno de los puntos de la practica (enlista actividades realizadas de acuerdo a la norma Moprosoft y realiza un ejercicio de complejidad ciclomatica).
Describe cada uno de los pasos realizados, describe los resultados obtenidos, incluye una introducción, lista de figuras, objetivo de la practica y  una conclusión.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
